### PR TITLE
changes for text size for screen resolution

### PR DESCRIPTION
**Pull request by iJamesss**

### CODE REVIEW

**Comment by Halen84** [comment]
This change doesn't really make much sense to me since right below this code, I'm using `FindWindowA` and `GetWindowRect`, but I guess this is good for setting an initial value if that fails (?).

I'll merge this if you change `g_screenHeight` set to `GetSystemMetrics(SM_CYSCREEN)`
```
int g_screenWidth = GetSystemMetrics(SM_CXSCREEN);
int g_screenHeight = GetSystemMetrics(SM_CYSCREEN);
```

**Comment by iJamesss** [comment]
getsystemmetrics finds the current resolution in pixels of a primary display, so both those values would result in being 1920 for width 1080 for height if was using that resolution vice versa for any resolution, i did test on a 1440 by 2560 monitor

**Comment by Halen84** [comment]
On your 2560x1440 monitor, do they get set to the appropriate values with `GetWindowRect`? Or is `GetSystemMetrics` required?

**Comment by iJamesss** [comment]
getwindowrect didnt completely look correct with my resolution only when i swapped to using getsystemmetrics it look appropriately correct

**Comment by Halen84** [comment]
Did you comment out the `SetResolution` code when you did that, or did you leave it and it still worked?

**Comment by iJamesss** [comment]
i left it and it worked

**Comment by Halen84** [comment]
Hmm alright. If you make these changes I'll merge this. I tested this in-game and it worked fine for me at least.
```cpp
int g_screenWidth = GetSystemMetrics(SM_CXSCREEN);
int g_screenHeight = GetSystemMetrics(SM_CYSCREEN);
```
Take a look at my comment on #4 if you haven't already.

**Pull request merged**
