### PR TITLE
fix text size for screen resolution

### PR DESCRIPTION
**Pull request by iJamesss**

### CODE REVIEW

**Comment by Halen84** [comment]
Not sure about this one. `1920` and `GetSystemMetrics(SM_CXSCREEN)` would more or less just output the exact same result no matter the actual game resolution size. It's just that one method is way less expensive to use over the other since this function will be called hundreds of thousands of times.

Using `1920` would still scale properly I believe. I just tested this in-game and they both do the same thing.

**Comment by iJamesss** [comment]
reason for the change was the text size seemed alot larger on my 2560p monitor once the that change was made it seemed to look appropriately correct, otherwise if was left at 1920 i would have to decrease the actual text size so current text size was 22 so i would have to make it 20 for it look okay

**Comment by iJamesss** [comment]
Red Dead Redemption 2_2022 11 25-16 41

with all the changes i applied this is how it looks on my monitor

**Comment by Halen84** [comment]
Is that what it looks like WITH your changes or WITHOUT your changes? Because the sizing for everything seems way off

**Comment by iJamesss** [comment]
thats with my changes, i will add another screen to see what you think if i left it at 1920

**Comment by iJamesss** [comment]
Red Dead Redemption 2_2022 11 25-18 08

this is if i left 1920 at the end instead of GetSystemMetrics

**Comment by iJamesss** [comment]
this another screen commented out the SetResolution but left GetSystemMetrics at the end of the line

Red Dead Redemption 2_2022 11 25-18 16

**Comment by Halen84** [comment]
The first picture is better, but the size for the menu itself is way off in all pictures. This is what it's supposed to look like (on a 1920x1080 monitor)

Red Dead Redemption 2 Screenshot 2022 11 25 - 12 25 28 41

**Comment by iJamesss** [comment]
yeah if i changed my resolution in game to 1920x1080 it does look exactly like that

**Comment by iJamesss** [comment]
so seems the menu shrinks by having higher resolution, so to my understanding you have to alter size of each drawable to make it look like it does on 1920x1080 for 2560x1440

**Comment by Halen84** [comment]
Should be improved with the latest update.

**Pull request closed without merging**
